# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3b1dbd2244e47ca6152ca0c87d5bfc79dcc3f56ca813a934c7250836863e539ab8d87486928f5c9c8cdbe57cd9bfaf47f04437189c5a403678fb0542a2dc611

test:
  secret_key_base: 5579aadb561250793edde9e9d0a180f865a16453815bdbd76fcc7a6143e3af6fc0bc4ddb7cc8fbbaf58063d29a814bcdae4b762f09cd6ecbb77e6672043e40a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
